In [ ]:
import torch
import numpy as np


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [ ]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
np_array=np.array(data)
print(np_array)

[[1 2]
 [3 4]]


In [ ]:
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [ ]:
x_one=torch.ones_like(x_data)
print(x_one)
x_random=torch.rand_like(x_data,dtype=torch.float)
print(x_data)
print(x_random)

tensor([[1, 1],
        [1, 1]])
tensor([[1, 2],
        [3, 4]])
tensor([[0.0455, 0.7783],
        [0.4209, 0.3727]])


In [ ]:
shape=(2,3)
shape2=(3,4)
rand_tensor=torch.rand(shape)
rand1_tensor=torch.rand(shape2)
print(rand_tensor)
print(rand1_tensor)

tensor([[0.7427, 0.9131, 0.3526],
        [0.7872, 0.5783, 0.6362]])
tensor([[0.9978, 0.3732, 0.6000, 0.2586],
        [0.5771, 0.0789, 0.9033, 0.1932],
        [0.2863, 0.6195, 0.9758, 0.9042]])


In [ ]:
tensor=torch.rand(2,2)
t1=torch.cat((tensor,tensor))
print(tensor)
print(t1)


tensor([[0.9182, 0.2816],
        [0.3836, 0.7393]])
tensor([[0.9182, 0.2816],
        [0.3836, 0.7393],
        [0.9182, 0.2816],
        [0.3836, 0.7393]])


In [ ]:
tensor=torch.rand(4,4)
print(tensor)
print(tensor[:,2])
print(tensor[2])
print(tensor[2,2])

tensor([[0.9216, 0.4079, 0.3595, 0.7186],
        [0.9460, 0.4607, 0.8406, 0.7361],
        [0.4387, 0.3437, 0.6567, 0.0520],
        [0.7974, 0.6115, 0.3148, 0.1661]])
tensor([0.3595, 0.8406, 0.6567, 0.3148])
tensor([0.4387, 0.3437, 0.6567, 0.0520])
tensor(0.6567)


In [ ]:
tensor1=torch.rand(2,2)
tensor2=torch.rand(2,2)
y3=torch.matmul(tensor1,tensor2)
y4=tensor1.matmul(tensor2)
y5=tensor1@tensor2
print(y3)
print(y4)
print(y5)
#all these codes produce the exact answer

tensor([[0.3746, 0.0492],
        [0.2261, 0.0363]])
tensor([[0.3746, 0.0492],
        [0.2261, 0.0363]])
tensor([[0.3746, 0.0492],
        [0.2261, 0.0363]])


In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y4=tensor.T

#tensor.T produces the transpose of the matrix



torch.matmul(tensor, tensor.T, out=y3)
print(f"y1 is:{y1}")
print(f"y2 is :{y2}")
print(f"y3 is :{tensor}")
print(f"y4 is :{y4}")

y1 is:tensor([[1.6613, 1.8909, 0.8179, 1.2169],
        [1.8909, 2.3557, 1.1637, 1.4230],
        [0.8179, 1.1637, 0.7445, 0.7754],
        [1.2169, 1.4230, 0.7754, 1.1365]])
y2 is :tensor([[1.6613, 1.8909, 0.8179, 1.2169],
        [1.8909, 2.3557, 1.1637, 1.4230],
        [0.8179, 1.1637, 0.7445, 0.7754],
        [1.2169, 1.4230, 0.7754, 1.1365]])
y3 is :tensor([[0.9216, 0.4079, 0.3595, 0.7186],
        [0.9460, 0.4607, 0.8406, 0.7361],
        [0.4387, 0.3437, 0.6567, 0.0520],
        [0.7974, 0.6115, 0.3148, 0.1661]])
y4 is :tensor([[0.9216, 0.9460, 0.4387, 0.7974],
        [0.4079, 0.4607, 0.3437, 0.6115],
        [0.3595, 0.8406, 0.6567, 0.3148],
        [0.7186, 0.7361, 0.0520, 0.1661]])


In [ ]:
agg=tensor.sum()
print(agg)
agg_value=round(agg.item(),3)
print(agg_value)
#here the .sum() function returns the sum of all elements in the tensor and the out is also a tensor
#if we need to strip down the tensor characters we need to use .item() which returns the normal value

tensor(8.7720)
8.772


In [ ]:
tensor=torch.ones(4,4)
print(f"{tensor}\n")
tensor.add_(5)#it adds in place that is no new tensor is created
tensor2=tensor.add(5)#a new tensor is created
print(tensor2)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [ ]:
#we can comfortably interchange between tensor and numpy
tensor=torch.ones(3,3)
print(tensor)
NpAcc=tensor.numpy()
print(NpAcc)
tensor2=torch.from_numpy(NpAcc)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import v2
import matplotlib.pyplot as plt

training_data=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=v2.Compose([v2.ToImage(),v2.ToDtype(torch.float32,scale=True)])
)
test_data=datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=v2.Compose([v2.ToImage(),v2.ToDtype(torch.float32,scale=True)])

)

100%|██████████| 26.4M/26.4M [00:01<00:00, 18.2MB/s]
100%|██████████| 29.5k/29.5k [00:00<00:00, 272kB/s]
100%|██████████| 4.42M/4.42M [00:00<00:00, 5.07MB/s]
100%|██████████| 5.15k/5.15k [00:00<00:00, 11.2MB/s]
